### ISSUE TITLE
Marked.js Rendering Issue

### ISSUE THREAD

**Issue by rakeen** [forthright48/website-v2#6]
This route here [Gateway -> Rare Topics -> Wilson's Theorem](http://www.forthright48.com/gateway/read/56efa2450b69bb03007f7cba) gives a 500 status.
![image](https://cloud.githubusercontent.com/assets/10359412/17482071/f4b7b5fc-5da1-11e6-895a-5101d38397c2.png)

**Comment by forthright48** [comment]
Thanks for pointing that out. I changed my schema, but didn't bother to change all documents to adapt to the new schema. If you find more like this, please let me know.
